"""Add likes table

Revision ID: fffe1bf6d616
Revises: 
Create Date: 2024-06-22 21:24:23.587441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffe1bf6d616'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_message_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint('likes_message_id_key', ['message_id'])

    # ### end Alembic commands ###
